---
# tasks file for nlsr
- name: install nlsr
  apt: name=nlsr state=latest update_cache=yes

- name: create nlsr user
  user: name=nlsr state=present shell=/bin/bash createhome=yes home=/home/nlsr

- name: create nlsr directories
  file: path=/etc/ndn/nlsr/keys state=directory owner=nlsr group=nlsr mode=0755
- file: path=/var/lib/ndn/nlsr state=directory owner=nlsr group=nlsr mode=0755
- file: path=/var/log/ndn/nlsr state=directory owner=nlsr group=nlsr mode=0755

- name: create nlsr.conf
  #template: src=nlsr.conf.j2 dest=/etc/ndn/nlsr/ansible_nlsr.conf owner=nlsr group=nlsr mode="u=rw,g=r,o=r"
  template: src=nlsr.conf.j2 dest=/etc/ndn/nlsr/nlsr.conf owner=nlsr group=nlsr mode="u=rw,g=r,o=r"
  notify: restart nlsr

- name: create key_gen.sh
  template: src=key_gen.j2 dest=/etc/ndn/nlsr/keys/key_gen.sh owner=nlsr group=nlsr mode="u=rw,g=r,o=r"

- name: create log4cxx.conf
  copy: dest=/etc/ndn/nlsr/log4cxx.conf src=roles/nlsr/files/log4cxx.conf owner=root group=root mode=0644
  notify: restart nlsr

- name: start nlsr
  service: name=nlsr state=started enabled=yes
