---
# tasks file for nfd-autoreg
- name: install nfd-autoreg
  apt: name=nfd-autoreg state=present

- name: create /var/lib/ndn/nfd-autoreg
  file: path=/var/lib/ndn/nfd-autoreg state=directory owner=ndn group=ndn mode=0755

- name: create /etc/default/nfd-autoreg
  template: src=nfd-autoreg.j2 dest=/etc/default/ansible_nfd-autoreg owner=root group=root mode="u=rw,g=r,o=r"

- name: start nfd-autoreg
  service: name=nfd-autoreg state=started enabled=yes
