---
- name: collect stats from testbed nodes
  gather_facts: no
  hosts: ndngateways 
  remote_user: ndnops
  become: yes


  roles: 
  - {role: 'collectStatsFromAllNodes', tags: 'collectStatsFromAllNodes'} 

