---
- name: install experimental ndn gateways
  hosts: ndn_exp_gws
  remote_user: ndnops
  become: yes
#
  roles: 
  - NOC
  - ndn-cxx-from-source
  - nfd-from-source
  - ndn-tools-from-source
  - ndnsec
  - ndnping
  - nlsr-from-source
  - nfd-status-http-server
  - ndn-autoconfig-server
  - repo-ng
  - ndnmap-data-collector
  - ndnTestbedDataCollector
  - nfd-autoreg


#- name: install ndndemo
#  hosts: ndndemo
#  remote_user: jdd
#  become: yes
#
#  roles:
#  - nfd

