---
- name: start nlsr on all testbed nodes
  hosts: ndngateways 
  remote_user: ndnops
  become: yes


  roles: 
  - {role: 'nlsr_start', tags: 'nlsr_start'}  # to use the tag, do this:   > ansible-playbook -i testbedInventory --tags "nlsr_start"

