---

#- name: install a new ndncert-ca including root key
#  hosts: nightlybuilds
#  remote_user: ndnops
#  become: yes
#

- name: update ndncert-ca 
  hosts: ppabuilds 
  remote_user: ndnops
  become: yes


  roles: 
  - {role: 'ndncert-ca', tags: 'ndncert-ca'}  # 

