---

#- name: refresh an existing ndncert-site-ca. Will NOT create a new site key
#  hosts: nightlybuilds
#  remote_user: ndnops
#  become: yes
#

- name: install a new ndncert-site-ca including site key
  hosts: ppabuilds 
  remote_user: ndnops
  become: yes


  roles: 
  - {role: 'ndncert-site-ca', tags: 'ndncert-site-ca'}  # 

