---
- name: install ndn gateways (Ubuntu)
  gather_facts: no
  hosts: ndngateways 
  remote_user: ndnops
  become: yes


  roles: 
  - {role: 'cert_operator_domain_db_gen', tags: 'cert_operator_domain_db_gen'} 

