---
# tasks file for ndn-nightly-builds---

- name: JDD purge ndn packages (ndn-cxx, nfd, ndnsec)
  apt:
    name: ['ndn-cxx', 'nfd-autoreg', 'nfd', 'ndnsec', 'nlsr', 'libndn-cxx', 'libndn-cxx-dev', 'libndn-cxx-dbg' , 'libndncert', 'libpsync', 'ndn-autoconfig-server','ndn-dissect', 'ndn-tools', 'ndnchunks', 'ndndump', 'ndnpeek', 'ndnping', 'repo-ng' , 'nfd-status-http-server', 'infoedit' ]
    update_cache: yes
    autoclean: yes
    autoremove: no
    purge: yes
    state: absent
  when: ansible_distribution == "Ubuntu" 

# disable serve-certs systemd service
- name: disable serve-certs systemd service
  systemd: 
    name: serve-certs.service
    enabled: no
    masked: no
  ignore_errors: yes

# make uninstall on ndn6-tools
- make:
    chdir: /home/{{ansible_user}}/ndn6-tools
    target: uninstall
  become: yes
  ignore_errors: yes

# Remove ndn ppa
- command: add-apt-repository -y -r ppa:named-data/ppa
  become: yes

# Remove ndn ppa-dev
- command: add-apt-repository -y -r ppa:named-data/ppa-dev
  become: yes

- name: remove all named-data sources lists
  shell: rm -f /etc/apt/sources.list.d/*named*data*.list*

- name: add /etc/apt/sources.list.d/nfd-nightly.list for Ubuntu 20.04
  copy: dest=/etc/apt/sources.list.d/nfd-nightly.list src=roles/ndn-nightly-builds/files/ubuntu_20.04_sources.list mode=644 
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version  == "20")

- name: add /etc/apt/sources.list.d/nfd-nightly.list for Ubuntu 22.04
  copy: dest=/etc/apt/sources.list.d/nfd-nightly.list src=roles/ndn-nightly-builds/files/ubuntu_22.04_sources.list mode=644 
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version  == "22")

- name: JDD install ndn packages (nfd, ndnsec)
  apt:
    name: ['nfd', 'ndnsec', 'nlsr', 'libndn-cxx', 'libndn-cxx-dev', 'libndncert', 'ndncert-server','libpsync', 'nfd-autoreg', 'ndn-autoconfig-server','ndn-dissect', 'ndn-tools', 'ndnchunks', 'ndndump', 'ndnpeek', 'ndnping', 'repo-ng' , 'nfd-status-http-server', 'ndn6-tools', 'infoedit' ]
    # there's seems no nfd-autoreg now. I also don't think anyone is using autoreg
    # name: ['nfd', 'ndnsec', 'nlsr', 'libndn-cxx', 'libndn-cxx-dev', 'libndn-cxx-dbg', 'libpsync', 'ndn-autoconfig-server','ndn-dissect', 'ndn-tools', 'ndnchunks', 'ndndump', 'ndnpeek', 'ndnping', 'repo-ng' , 'nfd-status-http-server', 'ndn6-tools' ]
    update_cache: yes
    autoclean: yes
    autoremove: yes
    state: latest
  when: ansible_distribution == "Ubuntu" 

# enable ndn6-serve-certs systemd service
- name: enable ndn6-serve-certs systemd service
  systemd: 
    name: ndn6-serve-certs.service
    enabled: yes
    state: started
    masked: no

# now remove the nightly list so we don't get nodes out of sync or potentially troublesome versions installed from nightly/weekly
- name: remove nightly sources list for Ubuntu 20.04
  file: path=/etc/apt/sources.list.d/nfd-nightly.list state=absent
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version  == "20")

- name: remove nightly sources list for Ubuntu 22.04
  file: path=/etc/apt/sources.list.d/nfd-nightly.list state=absent
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version  == "22")
