---
# tasks file for nfd
- name: add ndn user
  user: name=ndn state=present shell=/bin/false createhome=no

#- name: add ndnsec user
#  user: name=ndnsec state=present shell=/bin/bash password=LrVkOUM1s16xE

- name: make ndn required directories
  file: path=/etc/ndn state=directory owner=ndn group=ndn mode=0755
- file: path=/etc/ndn/keys state=directory owner=ndn group=ndn mode=0755
- file: path=/etc/ndn/keys/anchors state=directory owner=ndn group=ndn mode=0755
- file: path=/var/lib/ndn state=directory owner=ndn group=ndn mode=0755
- file: path=/var/log/ndn state=directory owner=ndn group=ndn mode=0755

- name: set up rsyslog for nfd.log for Ubuntu 16.04
  copy: dest=/etc/rsyslog.d/25-nfd.conf src=roles/nfd/files/rsyslogd.25-nfd.conf owner=root group=root mode=0644
  when: (ansible_distribution == "Ubuntu" )

- name: initialize nfd.log
  file: path=/var/log/ndn/nfd.log state=touch owner=syslog group=adm mode=0644
  when: (ansible_distribution == "Ubuntu" )

#- cron: name="log rotate" user="{{ansible_user}}" hour="1" minute="1" job="/home/{{ansible_user}}/ndn-ops/NOC/logRotation/rotateLogs.sh  "
- cron: name="log rotate" state="absent" user="{{ansible_user}}" minute="28" job="/home/{{ansible_user}}/ndn-ops/NOC/bin/rotateLogs.sh  "

- name: copy logrotate conf file for nfd
  copy: dest=/etc/logrotate.d/nfd  src=roles/nfd/files/logrotate.nfd owner=root group=root mode=0644

- name: remove ashlesh asf version of nfd if present
  apt: name=nfd=0.5.1-73-gc65c9be-ppa2~trusty state=absent update_cache=yes
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version  == "14")
  ignore_errors: yes

- name: remove ashlesh asf version of nfd if present
  apt: name=nfd=0.5.1-73-gc65c9be-ppa2~xenial state=absent update_cache=yes
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version  == "16")
  ignore_errors: yes

#- name: copy root key X2
#  copy: dest=/etc/ndn/keys/ndn-testbed-root.ndncert.x2.base64 src=roles/nfd/files/ndn-testbed-root.ndncert.x2.base64 owner=root group=root mode=0644
#
#- name: copy root key X3
#  copy: dest=/etc/ndn/keys/ndn-testbed-root.ndncert.x3.base64 src=roles/nfd/files/ndn-testbed-root.ndncert.x3.base64 owner=root group=root mode=0644
#
- name: copy root key X2
  copy: dest=/etc/ndn/keys/anchors/ndn-testbed-root.ndncert.x2.base64 src=roles/nfd/files/ndn-testbed-root.ndncert.x2.base64 owner=root group=root mode=0644

- name: copy root key X3
  copy: dest=/etc/ndn/keys/anchors/ndn-testbed-root.ndncert.x3.base64 src=roles/nfd/files/ndn-testbed-root.ndncert.x3.base64 owner=root group=root mode=0644

#- name: copy openmhealth key
#  copy: dest=/etc/ndn/keys/openmhealth.cert src=roles/nfd/files/openmhealth.cert owner=root group=root mode=0644

- name: create nfd-init.sh
  #template: src=nfd-init.sh.j2 dest=/etc/ndn/ansible_nfd-init.sh  owner=root group=root mode="u=rwx,g=rx,o=rx"
  template: src=nfd-init.sh.j2 dest=/etc/ndn/nfd-init.sh  owner=root group=root mode="u=rwx,g=rx,o=rx"
  notify: restart nfd

- name: create nfd.conf
  #template: src=nfd.conf.j2 dest=/etc/ndn/ansible_nfd.conf owner=root group=root mode="u=rw,g=r,o=r"
  template: src=nfd.conf.j2 dest=/etc/ndn/nfd.conf owner=root group=root mode="u=rw,g=r,o=r"
  notify: restart nfd

#- name: install nfd
#  apt: name=nfd state=latest update_cache=yes

#- name: install nfd-dbg
#  apt: name=nfd-dbg state=latest update_cache=yes

#- name: start nfd
#  service: name=nfd state=started enabled=yes

# The problem is that we want to restart nfd sometimes before something like NLSR restarts
# and sometimes after NLSR restarts...
# restart nfd immediately, don't wait for end of playbook
#- meta: flush_handlers

