---
# tasks file for ndnTestbedDataCollector
- name: create /etc/default/ndnTestbedDataCollector
  #template: src=ndnTestbedDataCollector.j2 dest=/etc/default/ansible_ndnTestbedDataCollector owner=root group=root mode="u=rw,g=r,o=r"
  template: src=ndnTestbedDataCollector.j2 dest=/etc/default/ndnTestbedDataCollector owner=root group=root mode="u=rw,g=r,o=r"
  notify: restart ndnTestbedDataCollector

- name: start ndnTestbedDataCollector
  service: name=ndnTestbedDataCollector state=started enabled=yes

