---
# tasks file for ndnmap-data-collector
- name: install ndnmap-data-collector
  apt: name=ndnmap-data-collector state=present

- name: create /etc/default/ndnmap-data-collector
  template: src=ndnmap-data-collector.j2 dest=/etc/default/ansible_ndnmap-data-collector owner=root group=root mode="u=rw,g=r,o=r"

- name: start ndnmap-data-collector
  service: name=ndnmap-data-collector state=started enabled=yes
