---
# tasks file for repo-ng
- name: install repo-ng
  apt: name=repo-ng state=present

- name: create repo-ng configuration file
  #template: src=repo-ng.conf.j2 dest=/etc/ndn/ansible_repo-ng.conf owner=root group=root mode="u=rw,g=r,o=r"
  template: src=repo-ng.conf.j2 dest=/etc/ndn/repo-ng.conf owner=root group=root mode="u=rw,g=r,o=r"

- name: start repo-ng
  service: name=repo-ng state=started enabled=yes
